import { expect, test } from '@playwright/test';
test('documentary pages work without JavaScript, expose real links and keep indexing disabled', async ({ browser }, info) => {
  const context = await browser.newContext({ javaScriptEnabled: false, viewport: info.project.name === 'mobile' ? { width: 390, height: 844 } : { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const errors: string[] = [], remote: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (!request.url().startsWith('http://127.0.0.1:4300/')) remote.push(request.url()); });
  const response = await page.goto('http://127.0.0.1:4300/entite/Q30527240');
  expect(response?.status()).toBe(200);
  await expect(page.getByRole('heading', { level: 1, name: 'Albane Gaillot', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Explorer ce réseau', exact: true })).toHaveAttribute('href', /root=Q30527240/);
  await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content', /noindex/);
  await expect(page.locator('link[rel="canonical"]')).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'Méthode et couverture', exact: true }).first()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: `.working/sprint/lot4-entity-top-${info.project.name}.png`, fullPage: false, scale: 'css' });
  await page.locator('.document-relation summary').first().click();
  await expect(page.locator('.document-relation').first().getByRole('link').first()).toBeVisible();
  await page.screenshot({ path: `.working/sprint/lot4-entity-${info.project.name}.png`, fullPage: false, scale: 'css' });
  await page.getByRole('link', { name: 'Méthode et couverture', exact: true }).first().click();
  await expect(page.getByRole('heading', { level: 1, name: 'Méthode et couverture' })).toBeVisible();
  await page.goto('http://127.0.0.1:4300/entite/Q273579');
  await expect(page.getByRole('heading', { level: 1 })).toContainText('École nationale');
  await expect(page.locator('.document-relation').first()).toBeAttached();
  const missing = await page.goto('http://127.0.0.1:4300/entite/entite-inconnue');
  expect(missing?.status()).toBe(404);
  const sitemap = await context.request.get('http://127.0.0.1:4300/sitemap.xml');
  expect(await sitemap.text()).not.toContain('<loc>');
  expect(errors).toEqual([]);
  expect(remote).toEqual([]);
  await context.close();
});
