import { DocumentLayout } from '@/components/DocumentLayout';
import Link from 'next/link';
import { loadDataset } from '@/lib/dataset';
import { documentMetadata } from '@/lib/publication';
import currentRoster from '../../../scripts/people-2026.json';
export const dynamic = 'force-dynamic';
export function generateMetadata() { return documentMetadata('Méthode et couverture', 'Sources, limites du corpus et règles de lecture des relations documentées dans Civigraph.', '/methode'); }
export default function MethodDocument() {
  const data = loadDataset();
  const wikidata = data.relations.filter(relation => !relation.evidence);
  const sourced = wikidata.filter(relation => relation.references.some(reference => reference.urls.length));
  const pictured = data.entities.filter(entity => entity.image);
  return <DocumentLayout><div className="document-title"><p className="eyebrow">Lire le corpus</p><h1>Méthode et couverture</h1><p>Comprendre ce qu’un lien documente, et ce qu’il ne permet pas de conclure.</p></div>
    <div className="document-statistics"><span><strong>{data.meta.peopleCount}</strong> personnes du corpus</span><span><strong>{data.entities.length}</strong> entités</span><span><strong>{data.relations.length}</strong> déclarations</span></div>
    <section className="document-prose"><h2>Un instantané exploratoire</h2><p>La sélection est non exhaustive et non représentative. Le corpus initial a été enrichi depuis douze écoles, entreprises et organisations. L’absence d’une personne ou d’un lien ne démontre pas leur absence dans la vie publique. Les données ne sont pas actualisées en continu.</p><p>Import initial : {new Date(data.meta.fetchedAt).toLocaleDateString('fr-FR', { timeZone: 'UTC' })}. Dernier complément : {new Date(data.meta.supplementedAt ?? data.meta.fetchedAt).toLocaleDateString('fr-FR', { timeZone: 'UTC' })}.</p>
    <h2>Des déclarations, avec leur provenance</h2><p>{wikidata.length} déclarations proviennent de Wikidata ; {sourced.length} comportent une URL de référence externe. Les autres sont à recouper, certaines citant une publication sans URL. {data.relations.length - wikidata.length} déclarations complémentaires renvoient à des documents publics identifiés.</p><p>Les sources comprennent les mandats de l’Assemblée nationale, les activités déclarées à la HATVP distribuées par Integrity Watch France et des compositions officielles. Les références, identifiants et précisions de dates restent attachés à chaque déclaration. Plusieurs sources d’un même fait ne deviennent pas plusieurs relations personnelles.</p>
    <h2>Des dates avec leurs limites</h2><p>Les dates au jour, au mois et à l’année conservent leur précision. Une borne absente n’est jamais complétée. Une année frontière commune ne suffit pas à établir un chevauchement certain. Les passages aux dates insuffisantes restent accessibles séparément.</p><p>« Même période » retient un chevauchement documenté ou une même composition officielle. Cela ne prouve pas une rencontre. « Même école » ne signifie pas « même promotion », et une fonction générique ne désigne pas nécessairement la même institution.</p>
    <h2>Lire la carte et les comparaisons</h2><p>L’année repère organise les couronnes de distance temporelle ; elle ne filtre pas les personnes en fonction cette année. Les couronnes sont des classes d’écart entre périodes, sans score d’influence. Les dates inconnues restent hors échelle et le parcours d’exploration reste distinct.</p><p>La comparaison relie les personnes à des entités communes et donne les preuves de chaque côté. Les chemins institutionnels alternent personnes et institutions, sur quatre segments au maximum et toutes périodes. Des chevauchements locaux ne prouvent pas que tout un chemin existait à une même date.</p>
    <h2>Consulter les sources publiques</h2><ul><li><a href="https://www.wikidata.org/wiki/Wikidata:Data_access/fr" target="_blank" rel="noopener noreferrer">Wikidata : accès aux données sous CC0</a></li><li><a href="https://data.assemblee-nationale.fr/acteurs/historique-des-deputes" target="_blank" rel="noopener noreferrer">Assemblée nationale : historique des députés</a></li><li><a href="https://www.integritywatch.fr/" target="_blank" rel="noopener noreferrer">Integrity Watch France</a></li><li><a href="https://www.hatvp.fr/open-data/" target="_blank" rel="noopener noreferrer">HATVP : données ouvertes</a></li></ul><p>Les documents et les éventuelles images conservent leurs propres conditions de réutilisation. La licence des données Wikidata ne s’étend pas automatiquement à ces contenus.</p></section>
    <section className="document-prose"><h2>Les images du corpus</h2><p>{pictured.length} entités possèdent une vignette locale, dont {pictured.filter(entity => entity.type === 'person').length} personnes. Les images proviennent de Wikimedia Commons, avec une association publique à l’identifiant de l’entité ou une alternative relue et sourcée. Leur choix ne décrit pas la personne à une date du parcours.</p><p>Le crédit de chaque image donne l’auteur, la licence, la source et la date photographique lorsqu’elle est renseignée. Les vignettes peuvent être recadrées à l’affichage ; leur licence reste attachée à l’image. Les images absentes ou non retenues ne sont pas remplacées par des portraits inventés. <a href="https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia" target="_blank" rel="noopener noreferrer">Conditions de réutilisation de Wikimedia Commons ↗</a></p></section>
    <section className="document-prose"><h2>Le socle politique de 2026</h2><p>{currentRoster.people.length} personnes ont été retenues à partir des sources consultées le 8 septembre 2026 : les 36 membres du gouvernement, les 11 présidences des groupes de l’Assemblée, les 7 présidences renseignées au Sénat et les responsables principaux de 13 formations. Certains cumulent plusieurs rôles.</p><p>Les formations retenues sont RN, Renaissance, LFI, PS, LR, Les Écologistes, PCF, MoDem, Horizons, UDI, Place publique, UDR et Reconquête. Ce périmètre éditorial ne couvre pas toutes les formations, leurs équipes dirigeantes complètes ou tous les élus. Les fonctions sont attestées à une date de consultation ; les parcours historiques peuvent rester incomplets.</p><p>Présidence du groupe RDPI au Sénat : non renseignée dans la <a href="https://www.senat.fr/senateurs/grp.html" target="_blank" rel="noopener noreferrer">liste consultée</a>. Aucun titulaire n’est supposé.</p><details><summary>Consulter les {currentRoster.people.length} personnes et leurs sources de sélection</summary><ul>{currentRoster.people.map(person => <li key={person.id}><Link href={`/entite/${person.id}`} prefetch={false}>{person.name}</Link><ul>{person.roles.map((role, index) => <li key={index}><a href={role.url} target="_blank" rel="noopener noreferrer">{role.role} · {role.organization}</a></li>)}</ul></li>)}</ul></details></section>
    <Link className="primary-button" href="/" prefetch={false}>Explorer la carte</Link>
  </DocumentLayout>;
}
