import { DocumentLayout } from '@/components/DocumentLayout';
import Link from 'next/link';
import { loadDataset } from '@/lib/dataset';
import { documentMetadata } from '@/lib/publication';
import currentRoster from '../../../scripts/people-2026.json';
import milieuCatalog from '@/data/institution-milieus.json';
import { MILIEUS } from '@/lib/network-insights';
export const dynamic = 'force-dynamic';
export function generateMetadata() { return documentMetadata('Sources et méthode', 'D’où viennent les informations de Civigraph ? Comment lire les dates, les liens et les comparaisons ?', '/methode'); }
export default function MethodDocument() {
  const data = loadDataset();
  const wikidata = data.relations.filter(relation => !relation.evidence);
  const sourced = wikidata.filter(relation => relation.references.some(reference => reference.urls.length));
  const pictured = data.entities.filter(entity => entity.image);
  return <DocumentLayout><div className="document-title"><p className="eyebrow">À propos des données</p><h1>Sources et méthode</h1><p>D’où viennent les informations, comment elles sont choisies et ce que les liens permettent de savoir.</p></div>
    <div className="document-statistics"><span><strong>{data.meta.peopleCount}</strong> personnes recensées</span><span><strong>{data.entities.length}</strong> fiches</span><span><strong>{data.relations.length}</strong> mentions</span></div>
    <section className="document-prose"><h2>Qui figure sur le site ?</h2><p>La sélection a commencé autour de douze écoles, entreprises et organisations, puis s’est élargie à d’autres responsables politiques. Elle reste incomplète et ne constitue pas un échantillon représentatif. Une personne ou un lien peut manquer simplement parce que nous ne l’avons pas encore ajouté. Les informations ne sont pas mises à jour en continu.</p><p>Import initial : {new Date(data.meta.fetchedAt).toLocaleDateString('fr-FR', { timeZone: 'UTC' })}. Dernier complément : {new Date(data.meta.supplementedAt ?? data.meta.fetchedAt).toLocaleDateString('fr-FR', { timeZone: 'UTC' })}.</p>
    <h2>D’où viennent les informations ?</h2><p>{wikidata.length} mentions proviennent de Wikidata ; {sourced.length} comportent une URL de référence externe. Les autres sont à recouper, certaines citant une publication sans URL. {data.relations.length - wikidata.length} mentions complémentaires renvoient à des documents publics identifiés.</p><p>Les sources comprennent les mandats de l’Assemblée nationale, les activités déclarées à la HATVP distribuées par Integrity Watch France et des compositions officielles. Les références, identifiants et précisions de dates restent attachés à chaque déclaration. Plusieurs sources d’un même fait ne deviennent pas plusieurs relations personnelles.</p>
    <h2>Comment lire les dates ?</h2><p>Les dates sont affichées avec la précision de la source : jour, mois ou année. Nous n’inventons pas les dates manquantes. Si une personne part et une autre arrive la même année, cela ne suffit pas à dire qu’elles étaient présentes en même temps. Les passages mal datés restent consultables séparément.</p><p>« Même période » retient un chevauchement documenté ou une même composition officielle. Cela ne prouve pas une rencontre. « Même école » ne signifie pas « même promotion », et une fonction générique ne désigne pas nécessairement la même institution.</p>
    <h2>Lire la carte et les comparaisons</h2><p>L’année repère organise les couronnes de distance temporelle ; elle ne filtre pas les personnes en fonction cette année. Les couronnes sont des classes d’écart entre périodes, sans score d’influence. Les dates inconnues restent hors échelle et le parcours d’exploration reste distinct.</p><p>La comparaison relie les personnes à des entités communes et donne les preuves de chaque côté. Les chemins institutionnels alternent personnes et institutions, sur quatre segments au maximum et toutes périodes. Des chevauchements locaux ne prouvent pas que tout un chemin existait à une même date.</p>
    <h2>Consulter les sources publiques</h2><ul><li><a href="https://www.wikidata.org/wiki/Wikidata:Data_access/fr" target="_blank" rel="noopener noreferrer">Wikidata : accès aux données sous CC0</a></li><li><a href="https://data.assemblee-nationale.fr/acteurs/historique-des-deputes" target="_blank" rel="noopener noreferrer">Assemblée nationale : historique des députés</a></li><li><a href="https://www.integritywatch.fr/" target="_blank" rel="noopener noreferrer">Integrity Watch France</a></li><li><a href="https://www.hatvp.fr/open-data/" target="_blank" rel="noopener noreferrer">HATVP : données ouvertes</a></li></ul><p>Les documents et les éventuelles images conservent leurs propres conditions de réutilisation. La licence des données Wikidata ne s’étend pas automatiquement à ces contenus.</p></section>
    <section className="document-prose"><h2>Les photos et les illustrations</h2><p>{pictured.length} fiches possèdent une image, dont {pictured.filter(entity => entity.type === 'person').length} personnes. Les images proviennent de Wikimedia Commons, avec une association publique à l’identifiant de l’entité ou une alternative relue et sourcée. Leur choix ne décrit pas la personne à une date du parcours.</p><p>Le crédit de chaque image donne l’auteur, la licence, la source et la date photographique lorsqu’elle est renseignée. Les vignettes peuvent être recadrées à l’affichage ; leur licence reste attachée à l’image. Les images absentes ou non retenues ne sont pas remplacées par des portraits inventés. <a href="https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia" target="_blank" rel="noopener noreferrer">Conditions de réutilisation de Wikimedia Commons ↗</a></p></section>
    <section className="document-prose"><h2>Les responsables politiques ajoutés en 2026</h2><p>{currentRoster.people.length} personnes ont été retenues à partir des sources consultées le 8 septembre 2026 : les 36 membres du gouvernement, les 11 présidences des groupes de l’Assemblée, les 7 présidences renseignées au Sénat et les responsables principaux de 13 formations. Certains cumulent plusieurs rôles.</p><p>Les formations retenues sont RN, Renaissance, LFI, PS, LR, Les Écologistes, PCF, MoDem, Horizons, UDI, Place publique, UDR et Reconquête. Ce périmètre éditorial ne couvre pas toutes les formations, leurs équipes dirigeantes complètes ou tous les élus. Les fonctions sont attestées à une date de consultation ; les parcours historiques peuvent rester incomplets.</p><p>Présidence du groupe RDPI au Sénat : non renseignée dans la <a href="https://www.senat.fr/senateurs/grp.html" target="_blank" rel="noopener noreferrer">liste consultée</a>. Aucun titulaire n’est supposé.</p><details><summary>Consulter les {currentRoster.people.length} personnes et leurs sources de sélection</summary><ul>{currentRoster.people.map(person => <li key={person.id}><Link href={`/entite/${person.id}`} prefetch={false}>{person.name}</Link><ul>{person.roles.map((role, index) => <li key={index}><a href={role.url} target="_blank" rel="noopener noreferrer">{role.role} · {role.organization}</a></li>)}</ul></li>)}</ul></details></section>
    <section className="document-prose"><h2>Cercles entre partis</h2><p>Cette vue rassemble des personnes passées par une même organisation et ayant appartenu à des partis différents. Elle utilise les déclarations de parti de Wikidata ; les groupes parlementaires et le statut indépendant ne sont pas comptés comme des partis. Les passages respectent les filtres de la carte, tandis que les appartenances sont recherchées dans l’ensemble des carrières.</p><p>« Au cours des carrières » peut rapprocher des faits d’époques différentes. « Au même moment, dates établies » exige une période commune aux deux passages et aux deux appartenances politiques. Une composition commune datée à l’année est retenue si les appartenances couvrent toute la période possible. Une fin manquante reste inconnue. Des partis différents ne sont pas nécessairement opposés, et un cercle partagé ne démontre pas une rencontre.</p><p>Dix participations Young Leaders, réparties entre les promotions 1982, 1996, 2006, 2011 et 2012, ont été recoupées dans l’<a href="https://www.french-american.org/programmes-et-evenements/young-leaders/" target="_blank" rel="noopener noreferrer">annuaire publié par la French-American Foundation France</a> le 8 septembre 2026. La participation au programme ne devient pas une adhésion à la Fondation. Cette sélection n’est pas exhaustive.</p><h2>Parcours entre milieux</h2><p>Les milieux sont une classification éditoriale partielle, par identifiant d’institution ou de fonction, complétée par les relations de formation et de parti. Une fonction explicitement contextualisée par une institution classée peut relever du même milieu. Un titre générique ou une simple ressemblance de nom ne suffit pas. Un passage dans une école ne prouve pas un emploi dans l’administration.</p><p>Les comptes portent sur les milieux distincts documentés, sans score d’influence. Les entités non classées restent signalées. Les fiches personnelles couvrent le parcours complet ; l’exploration respecte les filtres actifs.</p><details><summary>Institutions et fonctions retenues dans la classification</summary>{MILIEUS.filter(m => !['politics', 'education'].includes(m.id)).map(m => <section key={m.id}><h3>{m.label}</h3><ul>{milieuCatalog.entries.filter(e => e.milieu === m.id).map(e => <li key={e.id}><Link href={`/entite/${e.id}`} prefetch={false}>{e.label}</Link></li>)}</ul></section>)}</details></section>
    <Link className="primary-button" href="/" prefetch={false}>Explorer la carte</Link>
  </DocumentLayout>;
}
